name: flutter_kickstart
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sentry_flutter: ^9.16.0
  supabase_flutter: ^2.12.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  dart_pre_commit: ^6.1.1+1
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env